Tentative corrections
- scripts/save.py: changed order of tag & attrib assignments in do_command_aux_i (Sublime console was repeatedly spitting out a stacktrace ending with "AttributeError: 'dict' object has no attribute 'upper'" on line 329, and this seemed like the natural fix)
- exec_context.py: changed initial value of show_output_on_errors to True if show_panel_on_build and show are also True (since that seemed to make more sense)

If the original configurations weren't errors, feel free to disregard this commit.